### ISSUE TITLE
Envia para clientes desativados

### ISSUE THREAD

**Issue by linkincharles** [brlink-org/mkauth-recibo-pagamento#3]
quando cancela um cliente ele envia todos os comprovantes na madrugada para o cliente, teve um cliente que enviou mais de 100 comprovantes quando foi cancelado

**Comment by cirinho** [comment]
obrigado amigo, essa issue já foi aberta e resolvida #2 ... você já atualizou ?

**Comment by cirinho** [comment]
Após vc ter reportado lá no site do mk-auth em `https://mk-auth.com.br/forum/topics/rebido-de-pagamento-automatico-pelo-whatsapp` eu abri o chamado #2 onde acredito que tenha resolvido esse problema.

Como vc já tem a tabela e a trigger criada sugiro apagar e recriar mais fácil/prático ... ou caso vc tenha algum conhecimento em sql vc pode alterar a tabela a trigger pois houveram mudanças com objetivo de corrigir o problema.

Após vc atualizar espero que não volte a ocorrer, ao menos aqui está funcionando conforme esperado. Caso ainda note algo favor reportar.

Só não entendi o que é "cancelar" o cliente ... seria desativar ?

**Comment by cirinho** [comment]
@linkincharles vamos pegar agora somente os clientes ativos e que estejam marcado para receber mensagens via whatsapp.
